apiVersion: v1
kind: Pod
metadata:
  name: billsetuptask
spec:
  restartPolicy: Never
  containers:
    - name: task
      image: dev.local/billsetuptask:0.0.1-SNAPSHOT
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb:3306/mariadb
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.mariadb.jdbc.Driver
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password